spring:
  application:
    name: ms-reportes
  datasource:
    url: jdbc:mysql://${AIVEN_DB_HOST}:${AIVEN_DB_PORT}/informes_db?sslMode=REQUIRED&serverTimezone=UTC&createDatabaseIfNotExist=true
    username: ${AIVEN_DB_USER}
    password: ${AIVEN_DB_PASS}
    driver-class-name: com.mysql.cj.jdbc.Driver

logging:
  level:
    com.clinic: DEBUG
