server:
  port: 8085

spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: ms-reportes
  profiles:
    active: dev
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/informes_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_USERNAME:noreply@clinica.com}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka}
    registerWithEureka: true
    fetchRegistry: true

resilience4j:
  circuitbreaker:
    instances:
      citasService:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        failureRateThreshold: 50
  retry:
    instances:
      citasService:
        maxAttempts: 3
        waitDuration: 1000
        retryExceptions:
          - org.springframework.web.client.HttpServerErrorException
          - java.io.IOException
          - org.springframework.web.client.ResourceAccessException

feign:
  client:
    config:
      ms-pacientes:
        url: ${MS_PACIENTES_URL:http://localhost:8083}
      ms-citas:
        url: ${MS_CITAS_URL:http://localhost:8082}
      ms-usuarios:
        url: ${MS_USUARIOS_URL:http://localhost:8084}
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic
