server:
  port: 8092

spring:
  application:
    name: ms-auditoria
  profiles:
    active: dev

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka}
    register-with-eureka: true
    fetch-registry: true

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics
