spring:
  application:
    name: api-gateway-service
  data:
    redis:
      host: ${UPSTASH_REDIS_HOST}
      port: ${UPSTASH_REDIS_PORT}
      password: ${UPSTASH_REDIS_PASSWORD}
      ssl:
        enabled: ${UPSTASH_REDIS_SSL:true}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${AUTH0_ISSUER_URI}

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.security: DEBUG
    com.clinic.Gateway_Service: DEBUG
